/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package calculadora.de.nota;

import javax.swing.JOptionPane;

/**
 *
 * @author shing
 */
public class CalculadoraNota extends javax.swing.JPanel {

    
    /**
     * Creates new form CalculadoraNota
     */
    public CalculadoraNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Titulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnl_Input = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TxtF_Nombre = new javax.swing.JTextField();
        TxtF_Matricula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtF_Carrera = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        practicas = new javax.swing.JTextField();
        asignaciones = new javax.swing.JTextField();
        proyectoF = new javax.swing.JTextField();
        parciales = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        nota = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(153, 153, 153));
        Titulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Resgistro Académico");
        Titulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/de/nota/Imagenes/Adobe Express - file.png"))); // NOI18N
        Titulo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 60));

        pnl_Input.setBackground(new java.awt.Color(204, 204, 204));
        pnl_Input.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnl_Input.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nombre Completo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        TxtF_Nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtF_Nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        TxtF_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_NombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 560, -1));

        TxtF_Matricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        TxtF_Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_MatriculaActionPerformed(evt);
            }
        });
        TxtF_Matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtF_MatriculaKeyTyped(evt);
            }
        });
        jPanel1.add(TxtF_Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 250, -1));

        jLabel7.setText("Matricula:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel8.setText("Carrera:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        TxtF_Carrera.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        TxtF_Carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_CarreraActionPerformed(evt);
            }
        });
        jPanel1.add(TxtF_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 250, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("Informacion del estudiante");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 210, 50));

        pnl_Input.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 140));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Asignaciones  (15)");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel2.setText("Practicas (20)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel3.setText("Parciales (30)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, 20));

        jLabel4.setText("Proyecto final (35)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Calificaciones");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 80, 30));

        practicas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        practicas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        practicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practicasActionPerformed(evt);
            }
        });
        practicas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                practicasKeyTyped(evt);
            }
        });
        jPanel2.add(practicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 80, -1));

        asignaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        asignaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        asignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignacionesActionPerformed(evt);
            }
        });
        asignaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                asignacionesKeyTyped(evt);
            }
        });
        jPanel2.add(asignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, -1));

        proyectoF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        proyectoF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        proyectoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                proyectoFKeyTyped(evt);
            }
        });
        jPanel2.add(proyectoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 80, -1));

        parciales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        parciales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        parciales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                parcialesKeyTyped(evt);
            }
        });
        jPanel2.add(parciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 80, -1));

        pnl_Input.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 690, 120));

        calcular.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        calcular.setText("Calcular");
        calcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        pnl_Input.add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 80, 20));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel11.setText("Resultado ");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, -1, 40));

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel13.setText("Estado:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel14.setText("Nota:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        estado.setEditable(false);
        estado.setBackground(new java.awt.Color(153, 153, 153));
        estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        estado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        jPanel3.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 80, 30));

        nota.setEditable(false);
        nota.setBackground(new java.awt.Color(153, 153, 153));
        nota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaActionPerformed(evt);
            }
        });
        jPanel3.add(nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, 30));

        pnl_Input.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 690, 140));

        add(pnl_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtF_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_NombreActionPerformed

    private void TxtF_MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_MatriculaActionPerformed
        
    }//GEN-LAST:event_TxtF_MatriculaActionPerformed

    private void TxtF_CarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_CarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_CarreraActionPerformed

    private void TxtF_MatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtF_MatriculaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_MatriculaKeyTyped

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
       double valorAsignaciones =Double.parseDouble(this.asignaciones.getText());
       double valorPracticas = Double.parseDouble(this.practicas.getText());
       double valorParciales = Double.parseDouble(this.parciales.getText());
       double valorProyectoF = Double.parseDouble(this.proyectoF.getText());
       
       double sumaTotal = valorAsignaciones + valorPracticas + valorParciales + valorProyectoF;
       
       
       
       if (sumaTotal >100){
       JOptionPane.showMessageDialog(null, "error, tu nota excede los 100 puntos");
       }else{
       this.nota.setText(Double.toString(sumaTotal));
       }
       if (sumaTotal >= 60){
          this.estado.setText("Aprobado");
       }else {
          this.estado.setText("Reprobado");
       }
       
    }//GEN-LAST:event_calcularActionPerformed

    private void notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoActionPerformed

    private void asignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asignacionesActionPerformed

    private void asignacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_asignacionesKeyTyped
      char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.') && numeros != '\b') {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion");
            evt.consume();
        }
    }//GEN-LAST:event_asignacionesKeyTyped

    private void practicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_practicasActionPerformed

    private void practicasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_practicasKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.') && numeros != '\b') {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion");
            evt.consume();
        }      
    }//GEN-LAST:event_practicasKeyTyped

    private void parcialesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parcialesKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.') && numeros != '\b') {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion");
            evt.consume();
        }        
    }//GEN-LAST:event_parcialesKeyTyped

    private void proyectoFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proyectoFKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.') && numeros != '\b') {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion");
            evt.consume();
        }
    }//GEN-LAST:event_proyectoFKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Titulo;
    private javax.swing.JTextField TxtF_Carrera;
    private javax.swing.JTextField TxtF_Matricula;
    private javax.swing.JTextField TxtF_Nombre;
    private javax.swing.JTextField asignaciones;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField nota;
    private javax.swing.JTextField parciales;
    private javax.swing.JPanel pnl_Input;
    private javax.swing.JTextField practicas;
    private javax.swing.JTextField proyectoF;
    // End of variables declaration//GEN-END:variables
}
